[build-system]
requires = ["setuptools>=62.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-xmldjango"
description = "Django-XML template language grammar for tree-sitter"
version = "0.3.5"
keywords = ["incremental", "parsing", "tree-sitter", "xmldjango"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
authors = [{ name = "Laurent Putz", email = "laurent.putz@kraken.tech" }]
requires-python = ">=3.10"
license.text = "UNLICENSED"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/octoenergy/tree-sitter-xmldjango"

[project.optional-dependencies]
core = ["tree-sitter~=0.26"]

[dependency-groups]
dev = [
    "pre-commit>=3.0",
    "pytest>=8.0",
    "tree-sitter~=0.26",
]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
